### ISSUE TITLE
Generate Movies

### ISSUE THREAD

**Issue by acviana** [STScI-Citizen-Science/M83-Backend#2]
Generate ffmpeg movies from the images.

**Comment by acviana** [comment]
The images are in `/user/viana/m83/outputs` please generate one movie for each image size. You can write a shell script. Please add the script to the repo.

**Comment by prathamjoshi** [comment]
I wrote the little shell script for creating the movies but am not able to push it after I committed. I take it this is a permissions thing?

**Comment by acviana** [comment]
Yes, I think you are right. I could just change the permissions but instead let's use this a simple example to see if you can get a pull request generated using these [instructions](https://help.github.com/articles/using-pull-requests). From reading the docs I got the impression you would have to learn how to make a separate branch, but I'm not 100% sure on that. 

Have you already ran the script to create the movies then?

**Comment by prathamjoshi** [comment]
Yes, I had to fork to make a pull request. I did and the pull request now appears on the main repo page. 
I did run the script locally (because I do not have write access to the M83 output directory) , do you want the outputs committed too or...?
